apiVersion: gateway.networking.k8s.io/v1
kind: LoadBalancerConfiguration
metadata:
  name: roboshop-alb
  namespace: roboshop
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
  - protocolPort: HTTPS:443
    certificates:
    - arn:aws:acm:us-east-1:209115427888:certificate/7721c21f-c1de-4d00-a073-cd99d5f2db7d

 
